YoungsterPic::     INCBIN "gfx/trainers/trainers/youngster.pic"
BugCatcherPic::    INCBIN "gfx/trainers/trainers/bugcatcher.pic"
LassPic::          INCBIN "gfx/trainers/trainers/lass.pic"
SailorPic::        INCBIN "gfx/trainers/trainers/sailor.pic"
JrTrainerMPic::    INCBIN "gfx/trainers/trainers/jr.trainerm.pic"
JrTrainerFPic::    INCBIN "gfx/trainers/trainers/jr.trainerf.pic"
PokemaniacPic::    INCBIN "gfx/trainers/trainers/pokemaniac.pic"
SuperNerdPic::     INCBIN "gfx/trainers/trainers/supernerd.pic"
HikerPic::         INCBIN "gfx/trainers/trainers/hiker.pic"
BikerPic::         INCBIN "gfx/trainers/trainers/biker.pic"
BurglarPic::       INCBIN "gfx/trainers/trainers/burglar.pic"
EngineerPic::      INCBIN "gfx/trainers/trainers/engineer.pic"
FisherPic::        INCBIN "gfx/trainers/trainers/fisher.pic"
SwimmerPic::       INCBIN "gfx/trainers/trainers/swimmer.pic"
CueBallPic::       INCBIN "gfx/trainers/trainers/cueball.pic"
GamblerPic::       INCBIN "gfx/trainers/trainers/gambler.pic"
BeautyPic::        INCBIN "gfx/trainers/trainers/beauty.pic"
PsychicPic::       INCBIN "gfx/trainers/trainers/psychic.pic"
RockerPic::        INCBIN "gfx/trainers/trainers/rocker.pic"

;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Adding Swimmer ♀ Trainer
;;;;;;;;;;;;;;;;;;;;;;;;;;;
SwimmerFPic::      INCBIN "gfx/trainers/trainers/swimmerf.pic"

JugglerPic::       INCBIN "gfx/trainers/trainers/juggler.pic"
TamerPic::         INCBIN "gfx/trainers/trainers/tamer.pic"
BirdKeeperPic::    INCBIN "gfx/trainers/trainers/birdkeeper.pic"
BlackbeltPic::     INCBIN "gfx/trainers/trainers/blackbelt.pic"
Rival1Pic::        INCBIN "gfx/trainers/trainers/rival1.pic"
ProfOakPic::       INCBIN "gfx/trainers/trainers/prof.oak.pic"
ChiefPic::
ScientistPic::     INCBIN "gfx/trainers/trainers/scientist.pic"
GiovanniPic::      INCBIN "gfx/trainers/trainers/giovanni.pic"
RocketPic::        INCBIN "gfx/trainers/trainers/rocket.pic"
CooltrainerMPic::  INCBIN "gfx/trainers/trainers/cooltrainerm.pic"
CooltrainerFPic::  INCBIN "gfx/trainers/trainers/cooltrainerf.pic"
BrunoPic::         INCBIN "gfx/trainers/trainers/bruno.pic"
BrockPic::         INCBIN "gfx/trainers/trainers/brock.pic"
MistyPic::         INCBIN "gfx/trainers/trainers/misty.pic"
LtSurgePic::       INCBIN "gfx/trainers/trainers/lt.surge.pic"
ErikaPic::         INCBIN "gfx/trainers/trainers/erika.pic"
KogaPic::          INCBIN "gfx/trainers/trainers/koga.pic"
BlainePic::        INCBIN "gfx/trainers/trainers/blaine.pic"
SabrinaPic::       INCBIN "gfx/trainers/trainers/sabrina.pic"
GentlemanPic::     INCBIN "gfx/trainers/trainers/gentleman.pic"
Rival2Pic::        INCBIN "gfx/trainers/trainers/rival2.pic"
Rival3Pic::        INCBIN "gfx/trainers/trainers/rival3.pic"
LoreleiPic::       INCBIN "gfx/trainers/trainers/lorelei.pic"
ChannelerPic::     INCBIN "gfx/trainers/trainers/channeler.pic"
AgathaPic::        INCBIN "gfx/trainers/trainers/agatha.pic"
LancePic::         INCBIN "gfx/trainers/trainers/lance.pic"
;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Adding Soldier Trainer
;;;;;;;;;;;;;;;;;;;;;;;;;;;
;SoldierPic::       INCBIN "gfx/trainers/trainers/soldier.pic"
