;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Adding Party Menu ICONS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;

MonIcons::
;INCBIN "gfx/pokemon/icons/null.2bpp"		; null
INCBIN "gfx/pokemon/icons/bulbasaur.2bpp"   ; bulbasaur
;INCBIN "gfx/pokemon/icons/ivysaur.2bpp"     ; ivysaur
;INCBIN "gfx/pokemon/icons/venusaur.2bpp"    ; venusaur
INCBIN "gfx/pokemon/icons/charmander.2bpp"  ; charmander
;INCBIN "gfx/pokemon/icons/charmeleon.2bpp"  ; charmeleon
;INCBIN "gfx/pokemon/icons/charizard.2bpp"   ; charizard
INCBIN "gfx/pokemon/icons/squirtle.2bpp"    ; squirtle
;INCBIN "gfx/pokemon/icons/wartortle.2bpp"   ; wartortle
;INCBIN "gfx/pokemon/icons/blastoise.2bpp"   ; blastoise
INCBIN "gfx/pokemon/icons/caterpie.2bpp"    ; caterpie
;INCBIN "gfx/pokemon/icons/metapod.2bpp"     ; metapod
;INCBIN "gfx/pokemon/icons/butterfree.2bpp"  ; butterfree
INCBIN "gfx/pokemon/icons/weedle.2bpp"      ; weedle
;INCBIN "gfx/pokemon/icons/kakuna.2bpp"      ; kakuna
;INCBIN "gfx/pokemon/icons/beedrill.2bpp"    ; beedrill
INCBIN "gfx/pokemon/icons/pidgey.2bpp"      ; pidgey
;INCBIN "gfx/pokemon/icons/pidgeotto.2bpp"   ; pidgeotto
;INCBIN "gfx/pokemon/icons/pidgeot.2bpp"     ; pidgeot
INCBIN "gfx/pokemon/icons/rattata.2bpp"     ; rattata
;INCBIN "gfx/pokemon/icons/raticate.2bpp"    ; raticate
INCBIN "gfx/pokemon/icons/spearow.2bpp"     ; spearow
;INCBIN "gfx/pokemon/icons/fearow.2bpp"      ; fearow
INCBIN "gfx/pokemon/icons/ekans.2bpp"       ; ekans
;INCBIN "gfx/pokemon/icons/arbok.2bpp"       ; arbok
INCBIN "gfx/pokemon/icons/pikachu.2bpp"     ; pikachu
;INCBIN "gfx/pokemon/icons/raichu.2bpp"      ; raichu
INCBIN "gfx/pokemon/icons/sandshrew.2bpp"   ; sandshrew
;INCBIN "gfx/pokemon/icons/sandslash.2bpp"   ; sandslash
INCBIN "gfx/pokemon/icons/nidoran_f.2bpp"   ; nidoran_f
;INCBIN "gfx/pokemon/icons/nidorina.2bpp"    ; nidorina
;INCBIN "gfx/pokemon/icons/nidoqueen.2bpp"   ; nidoqueen
INCBIN "gfx/pokemon/icons/nidoran_m.2bpp"   ; nidoran_m
;INCBIN "gfx/pokemon/icons/nidorino.2bpp"    ; nidorino
;INCBIN "gfx/pokemon/icons/nidoking.2bpp"    ; nidoking
INCBIN "gfx/pokemon/icons/clefairy.2bpp"    ; clefairy
;INCBIN "gfx/pokemon/icons/clefable.2bpp"    ; clefable
INCBIN "gfx/pokemon/icons/vulpix.2bpp"      ; vulpix
;INCBIN "gfx/pokemon/icons/ninetales.2bpp"   ; ninetales
INCBIN "gfx/pokemon/icons/jigglypuff.2bpp"  ; jigglypuff
;INCBIN "gfx/pokemon/icons/wigglytuff.2bpp"  ; wigglytuff
INCBIN "gfx/pokemon/icons/zubat.2bpp"       ; zubat
;INCBIN "gfx/pokemon/icons/golbat.2bpp"      ; golbat
INCBIN "gfx/pokemon/icons/oddish.2bpp"      ; oddish
;INCBIN "gfx/pokemon/icons/gloom.2bpp"       ; gloom
;INCBIN "gfx/pokemon/icons/vileplume.2bpp"   ; vileplume
INCBIN "gfx/pokemon/icons/paras.2bpp"       ; paras
;INCBIN "gfx/pokemon/icons/parasect.2bpp"    ; parasect
INCBIN "gfx/pokemon/icons/venonat.2bpp"     ; venonat
;INCBIN "gfx/pokemon/icons/venomoth.2bpp"    ; venomoth
INCBIN "gfx/pokemon/icons/diglett.2bpp"     ; diglett
;INCBIN "gfx/pokemon/icons/dugtrio.2bpp"     ; dugtrio
INCBIN "gfx/pokemon/icons/meowth.2bpp"      ; meowth
;INCBIN "gfx/pokemon/icons/persian.2bpp"     ; persian
INCBIN "gfx/pokemon/icons/psyduck.2bpp"     ; psyduck
;INCBIN "gfx/pokemon/icons/golduck.2bpp"     ; golduck
INCBIN "gfx/pokemon/icons/mankey.2bpp"      ; mankey
;INCBIN "gfx/pokemon/icons/primeape.2bpp"    ; primeape
INCBIN "gfx/pokemon/icons/growlithe.2bpp"   ; growlithe
;INCBIN "gfx/pokemon/icons/arcanine.2bpp"    ; arcanine
INCBIN "gfx/pokemon/icons/poliwag.2bpp"     ; poliwag
;INCBIN "gfx/pokemon/icons/poliwhirl.2bpp"   ; poliwhirl
;INCBIN "gfx/pokemon/icons/poliwrath.2bpp"   ; poliwrath
INCBIN "gfx/pokemon/icons/abra.2bpp"        ; abra
;INCBIN "gfx/pokemon/icons/kadabra.2bpp"     ; kadabra
;INCBIN "gfx/pokemon/icons/alakazam.2bpp"    ; alakazam
INCBIN "gfx/pokemon/icons/machop.2bpp"      ; machop
;INCBIN "gfx/pokemon/icons/machoke.2bpp"     ; machoke
;INCBIN "gfx/pokemon/icons/machamp.2bpp"     ; machamp
INCBIN "gfx/pokemon/icons/bellsprout.2bpp"  ; bellsprout
;INCBIN "gfx/pokemon/icons/weepinbell.2bpp"  ; weepinbell
;INCBIN "gfx/pokemon/icons/victreebel.2bpp"  ; victreebel
INCBIN "gfx/pokemon/icons/tentacool.2bpp"   ; tentacool
;INCBIN "gfx/pokemon/icons/tentacruel.2bpp"  ; tentacruel
INCBIN "gfx/pokemon/icons/geodude.2bpp"     ; geodude
;INCBIN "gfx/pokemon/icons/graveler.2bpp"    ; graveler
;INCBIN "gfx/pokemon/icons/golem.2bpp"       ; golem
INCBIN "gfx/pokemon/icons/ponyta.2bpp"      ; ponyta
;INCBIN "gfx/pokemon/icons/rapidash.2bpp"    ; rapidash
INCBIN "gfx/pokemon/icons/slowpoke.2bpp"    ; slowpoke
;INCBIN "gfx/pokemon/icons/slowbro.2bpp"     ; slowbro
INCBIN "gfx/pokemon/icons/magnemite.2bpp"   ; magnemite
;INCBIN "gfx/pokemon/icons/magneton.2bpp"    ; magneton
INCBIN "gfx/pokemon/icons/farfetch_d.2bpp"  ; farfetch_d
INCBIN "gfx/pokemon/icons/doduo.2bpp"       ; doduo
;INCBIN "gfx/pokemon/icons/dodrio.2bpp"      ; dodrio
INCBIN "gfx/pokemon/icons/seel.2bpp"        ; seel
;INCBIN "gfx/pokemon/icons/dewgong.2bpp"     ; dewgong
INCBIN "gfx/pokemon/icons/grimer.2bpp"      ; grimer
;INCBIN "gfx/pokemon/icons/muk.2bpp"         ; muk
INCBIN "gfx/pokemon/icons/shellder.2bpp"    ; shellder
;INCBIN "gfx/pokemon/icons/cloyster.2bpp"    ; cloyster
INCBIN "gfx/pokemon/icons/gastly.2bpp"      ; gastly
;INCBIN "gfx/pokemon/icons/haunter.2bpp"     ; haunter
;INCBIN "gfx/pokemon/icons/gengar.2bpp"      ; gengar
INCBIN "gfx/pokemon/icons/onix.2bpp"        ; onix
INCBIN "gfx/pokemon/icons/drowzee.2bpp"     ; drowzee
;INCBIN "gfx/pokemon/icons/hypno.2bpp"       ; hypno
INCBIN "gfx/pokemon/icons/krabby.2bpp"      ; krabby
;INCBIN "gfx/pokemon/icons/kingler.2bpp"     ; kingler
INCBIN "gfx/pokemon/icons/voltorb.2bpp"     ; voltorb
;INCBIN "gfx/pokemon/icons/electrode.2bpp"   ; electrode
INCBIN "gfx/pokemon/icons/exeggcute.2bpp"   ; exeggcute
;INCBIN "gfx/pokemon/icons/exeggutor.2bpp"   ; exeggutor
INCBIN "gfx/pokemon/icons/cubone.2bpp"      ; cubone
;INCBIN "gfx/pokemon/icons/marowak.2bpp"     ; marowak
INCBIN "gfx/pokemon/icons/hitmon.2bpp" 		  ; hitmon
;INCBIN "gfx/pokemon/icons/hitmonlee.2bpp"   ; hitmonlee
;INCBIN "gfx/pokemon/icons/hitmonchan.2bpp"  ; hitmonchan
INCBIN "gfx/pokemon/icons/lickitung.2bpp"   ; lickitung
INCBIN "gfx/pokemon/icons/koffing.2bpp"     ; koffing
;INCBIN "gfx/pokemon/icons/weezing.2bpp"     ; weezing
INCBIN "gfx/pokemon/icons/rhyhorn.2bpp"     ; rhyhorn
;INCBIN "gfx/pokemon/icons/rhydon.2bpp"      ; rhydon
INCBIN "gfx/pokemon/icons/chansey.2bpp"     ; chansey
INCBIN "gfx/pokemon/icons/tangela.2bpp"     ; tangela
INCBIN "gfx/pokemon/icons/kangaskhan.2bpp"  ; kangaskhan
INCBIN "gfx/pokemon/icons/horsea.2bpp"      ; horsea
;INCBIN "gfx/pokemon/icons/seadra.2bpp"      ; seadra
INCBIN "gfx/pokemon/icons/goldeen.2bpp"     ; goldeen
;INCBIN "gfx/pokemon/icons/seaking.2bpp"     ; seaking
INCBIN "gfx/pokemon/icons/staryu.2bpp"      ; staryu
;INCBIN "gfx/pokemon/icons/starmie.2bpp"     ; starmie
INCBIN "gfx/pokemon/icons/mr__mime.2bpp"    ; mr__mime
INCBIN "gfx/pokemon/icons/scyther.2bpp"     ; scyther
INCBIN "gfx/pokemon/icons/jynx.2bpp"        ; jynx
INCBIN "gfx/pokemon/icons/electabuzz.2bpp"  ; electabuzz
INCBIN "gfx/pokemon/icons/magmar.2bpp"      ; magmar
INCBIN "gfx/pokemon/icons/pinsir.2bpp"      ; pinsir
INCBIN "gfx/pokemon/icons/tauros.2bpp"      ; tauros
INCBIN "gfx/pokemon/icons/magikarp.2bpp"    ; magikarp
;INCBIN "gfx/pokemon/icons/gyarados.2bpp"    ; gyarados
INCBIN "gfx/pokemon/icons/lapras.2bpp"      ; lapras
INCBIN "gfx/pokemon/icons/ditto.2bpp"       ; ditto
INCBIN "gfx/pokemon/icons/eevee.2bpp"       ; eevee
;INCBIN "gfx/pokemon/icons/vaporeon.2bpp"    ; vaporeon
;INCBIN "gfx/pokemon/icons/jolteon.2bpp"     ; jolteon
;INCBIN "gfx/pokemon/icons/flareon.2bpp"     ; flareon
INCBIN "gfx/pokemon/icons/porygon.2bpp"     ; porygon
INCBIN "gfx/pokemon/icons/omanyte.2bpp"     ; omanyte
;INCBIN "gfx/pokemon/icons/omastar.2bpp"     ; omastar
INCBIN "gfx/pokemon/icons/kabuto.2bpp"      ; kabuto
;INCBIN "gfx/pokemon/icons/kabutops.2bpp"    ; kabutops
INCBIN "gfx/pokemon/icons/aerodactyl.2bpp"  ; aerodactyl
INCBIN "gfx/pokemon/icons/snorlax.2bpp"     ; snorlax
INCBIN "gfx/pokemon/icons/articuno.2bpp"    ; articuno
INCBIN "gfx/pokemon/icons/zapdos.2bpp"      ; zapdos
INCBIN "gfx/pokemon/icons/moltres.2bpp"     ; moltres
INCBIN "gfx/pokemon/icons/dratini.2bpp"     ; dratini
;INCBIN "gfx/pokemon/icons/dragonair.2bpp"   ; dragonair
;INCBIN "gfx/pokemon/icons/dragonite.2bpp"   ; dragonite
INCBIN "gfx/pokemon/icons/mewtwo.2bpp"      ; mewtwo
INCBIN "gfx/pokemon/icons/mew.2bpp"         ; mew
;INCBIN "gfx/pokemon/icons/manboo.2bpp"     ; manboo 
;INCBIN "gfx/pokemon/icons/sankor.2bpp"   ; sankor
;INCBIN "gfx/pokemon/icons/grotesque.2bpp"   ; grotesque
